-- Seed from synthetic-kb.json, kept here for auditable SQL review.
INSERT INTO lab_customers(customer_id,customer_tier,customer_name) VALUES
('VTX-CUST-STARTER','starter','Cliente Fictício Essencial'),
('VTX-CUST-PRO','pro','Cliente Fictício Profissional'),
('VTX-CUST-ENTERPRISE','enterprise','Cliente Fictício Empresarial')
ON CONFLICT(customer_id) DO UPDATE SET customer_tier=EXCLUDED.customer_tier,customer_name=EXCLUDED.customer_name;

INSERT INTO knowledge_base (id, kind, intent, title, content, keywords) VALUES
('VTX-CAT-01','service_catalog','service_or_price','Diagnóstico e automação de processos','A Vértice IA diagnostica processos empresariais e identifica oportunidades de automação com IA. O escopo começa por descoberta e depende de avaliação do processo, dados e integrações.',ARRAY['diagnostico','processo','automacao','ia','servico']),
('VTX-CAT-02','service_catalog','service_or_price','Integrações e engenharia de software','A Vértice IA projeta integrações e soluções de software para operações empresariais. Escopo, prazo e faixa de investimento são definidos após levantamento técnico; não há preço fechado sem diagnóstico.',ARRAY['integracao','software','api','sistema','preco','valor','orcamento']),
('VTX-PRICE-01','price_range','service_or_price','Faixas de investimento de referência','Faixas exclusivamente ilustrativas para o laboratório: diagnóstico de R$ 2.000 a R$ 5.000; automação delimitada de R$ 8.000 a R$ 25.000; integração empresarial de R$ 12.000 a R$ 40.000. A proposta real exige descoberta e validação de escopo.',ARRAY['preco','faixa','investimento','custo','orcamento']),
('VTX-POL-01','policy','billing_or_contract','Cobrança e contratos exigem análise humana','Toda solicitação sobre cobrança, pagamento, reembolso, contrato, renovação ou obrigação comercial é encaminhada a uma pessoa responsável. O fluxo não interpreta nem altera condições contratuais.',ARRAY['cobranca','fatura','pagamento','reembolso','contrato','renovacao']),
('VTX-SLA-STARTER','sla','active_customer_ticket','SLA do plano Essencial','Cliente fictício da amostra no plano Essencial: incidente de baixa gravidade tem primeira resposta alvo em até 2 dias úteis; impacto alto exige avaliação humana prioritária. Não há atendimento 24/7 neste plano.',ARRAY['essencial','starter','plano','sla','incidente','gravidade','chamado','cliente']),
('VTX-SLA-PRO','sla','active_customer_ticket','SLA do plano Profissional','Cliente fictício da amostra no plano Profissional: incidente de média gravidade tem primeira resposta alvo em até 8 horas úteis; impacto crítico é encaminhado imediatamente a uma pessoa responsável.',ARRAY['profissional','pro','plano','sla','incidente','gravidade','chamado','cliente']),
('VTX-SLA-ENTERPRISE','sla','active_customer_ticket','SLA do plano Empresarial','Cliente fictício da amostra no plano Empresarial: incidente crítico tem primeira resposta alvo em até 1 hora; outros incidentes seguem prioridade acordada. A classificação final depende de revisão humana.',ARRAY['empresarial','enterprise','plano','sla','incidente','gravidade','chamado','cliente']),
('VTX-POL-02','policy','qualification','Descoberta para nova empresa','Para empresa nova, coletar setor, processo a melhorar, volume, sistemas envolvidos e resultado esperado. A triagem qualifica a conversa e encaminha para descoberta; não promete solução ou preço fechado.',ARRAY['empresa','nova','diagnostico','descoberta','setor','processo','volume','sistema'])
ON CONFLICT (id) DO UPDATE SET kind=EXCLUDED.kind,intent=EXCLUDED.intent,title=EXCLUDED.title,content=EXCLUDED.content,keywords=EXCLUDED.keywords,created_at=NOW();
